export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (id = ':id') => `/products/${id}`,
  SELLER_PROFILE: (id = ':id') => `/sellers/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDER_DETAIL: (id = ':id') => `/orders/${id}`,
  FAVORITES: '/favorites',
  MESSAGES: '/messages',
  PROFILE: '/profile',
  SELLER: {
    DASHBOARD: '/seller/dashboard',
    PRODUCTS: '/seller/products',
    CREATE_PRODUCT: '/seller/products/new',
    EDIT_PRODUCT: (id = ':id') => `/seller/products/${id}/edit`,
    ORDERS: '/seller/orders',
    STATISTICS: '/seller/statistics',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    PRODUCTS: '/admin/products',
    COUPONS: '/admin/coupons',
  },
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '/404',
}
